### ISSUE TITLE
[BUG]: GH Actions failing to checkout submodules

### ISSUE THREAD

**Issue by michael-pisman** [unipoll/Docs#2]
### Description of the bug

Input 'submodules' not supported when falling back to download using the GitHub REST API. To create a local Git repository instead, add Git 2.18 or higher to the PATH.

### Steps To Reproduce

Workflow
```
jobs:
    steps:
      - uses: actions/checkout@v3
        with:
        submodules: 'true'
```
